# Generated by Django 5.1.7 on 2025-04-22 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_acessorio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acessorio',
            options={'verbose_name': 'Acessório', 'verbose_name_plural': 'Acessórios'},
        ),
    ]
