# Generated by Django 5.1.7 on 2025-04-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_modelo_options_veiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='categoria',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
