# Generated by Django 5.1.7 on 2025-04-22 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_veiculo_categoria_alter_veiculo_preco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='categoria',
        ),
    ]
